superdesk/superdesk-planning

- server/planning/locations.py
- server/planning/planning.py
fixes POST for events resource
> fix(server): flake8 fixes and resource fixes

- server/app.py
- server/features/environment.py
- server/features/events.feature
- server/features/locations.feature
- server/features/planning.feature
- server/features/steps/__init__.py
- server/features/steps/steps.py
- server/planning/__init__.py
- server/planning/events.py
- server/planning/locations.py
- server/planning/planning.py
- server/requirements.txt
- server/settings.py
also added required app and settings files to be able to run behave tests directly from this code base.
> feature(server): add locations model and behave tests

- client/actions/index.js
- client/controllers/PlanningModalController.js
poke @petrjasek : a better way IMO to use ng services in my actions
> use of thunkMiddleware.withExtraArgument to inject ng services in actions

- client/actions/planning.js
- client/components/PlanningItem.jsx
And show location and date in plannings
> Nested event in plannings

- client/actions/planning.js
- client/components/SelectAgenda.jsx
- client/controllers/PlanningController.js
- client/reducers/planning.js
- client/selectors/index.js
Selected agenda id is now in the url as `?agenda=:agenda_id`.
This agenda will be selected on initialisation
> Agenda deep linking

- client/components/Event.jsx
- client/components/EventsList.jsx
- client/components/RepeatEventForm.jsx
- client/components/fields/DayPickerInput.jsx
- client/styles/events-list.scss
The checkboxes can be selected on click and the input will be focused
> Recuring date UI fixes

- client/components/PlanningItem.jsx
- client/components/PlanningPanelContainer.jsx
- client/styles/plannings.scss
adds a state to plannings list to show the active one
> Show active planning

- client/actions/events.js
- client/components/EventsListPanelContainer.jsx
- client/components/tests/AddEventForm_test.jsx
- client/components/tests/EditPlanningPanelContainer_test.jsx
- client/components/tests/EventsList_test.jsx
- client/controllers/PlanningController.js
- client/reducers/events.js
- client/reducers/tests/events_test.js
- client/selectors/index.js
- package.json
and update the url in order to allow to share the search page
> Search events

- client/components/tests/AddEventForm_test.jsx
- client/components/tests/EventsList_test.jsx
- client/reducers/events.js
- client/reducers/planning.js
- client/reducers/vocabularies.js
- client/utils/index.js
- package.json
- webpack.config.js
> Replace transform-object-assign by transform-object-rest-spread

- client/actions/events.js
- server/planning/events.py
Show submission errors in event form
Recurrence id is not unique
> Create unique id for recurrent events

- client/views/eventHttpConfig.html
- index.js
- server/planning/__init__.py
- server/planning/feed_parsers/ics_2_0.py
- server/planning/feed_parsers/ntb_event_xml.py
- server/planning/feeding_services/event_file_service.py
- server/planning/feeding_services/event_http_service.py
link http ingest service to existing ical parser
> Event http service

- client/components/Event.jsx
- client/components/fields/FileField.jsx
- client/components/tests/EventsList_test.jsx
- client/styles/events-list.scss
- client/styles/index.scss
Shows an icon in the event list if a file has been attached.
Shows how many.
> Attached file to events indicator

- client/components/ListItem/index.jsx
- client/components/ListItem/style.scss
- client/components/PlanningItem.jsx
a user can remove an event directly from an icon on the list
> planning context menu removed

- client/actions/events.js
- client/containers/EventsListPanelContainer/index.jsx
this call `loadEvevents` as a callback to `setState`
> Quick search value was chaging to the previous version

- package.json
> update sd-client-core and angular-mocks

- index.js
Depends on https://github.com/superdesk/superdesk-client-core/pull/1406
> [SDESK-88] Applying privilege while registering superdesk-planning item and activities

- client/actions/events.js
- client/containers/AdvancedSearchForm/_test.jsx
- client/containers/AdvancedSearchForm/index.jsx
Fix location search field
Category field added
Tests added for advanced search
> Adv search

- client/containers/AddEventForm/index.jsx
- client/containers/tests/RepeatEventForm_test.jsx
- client/reducers/forms.js
- client/validators/ChainValidators.js
when it says an initially filled field is required
> Fix issue with event form validation SDESK-894

- client/components/EventItem/index.jsx
Thanks to https://github.com/Hacker0x01/react-datepicker/pull/519
> [SDESK-850] Fix the height of DatePicker component as it moves position when it is mounted in top position

- server/planning/feed_parsers/ntb_event_xml_tests.py
- server/planning/feeding_services/event_file_service.py
this fixes ntb xml parsing issues
> fix(server): fix event file service from calling multiple parsers

- client/components/fields/LinkField.jsx
> use https with iframely

- client/actions/events.js
- client/components/EventsList/_test.jsx
- client/containers/EventForm/_test.jsx
> Allows to remove a location to an event

- package.json
Waiting for https://github.com/moment/moment-timezone/issues/466 being fixed
> Downgrade moment-timezone to 0.5.11

- client/components/PlanningItem.jsx
> Show a tooltip on planning removing button

- client/containers/ResizableEventsPanel/index.jsx
Use timeout on Resize selectively only for collapsing event panel
> [SDESK-1008] Use timeout on Resize selectively only for collapsing event panel

- client/actions/modal.js
- client/containers/ConfirmationModalContainer/index.jsx
- client/containers/EventForm/style.scss
- client/containers/EventsListContainer/index.jsx
- client/containers/PlanningPanelContainer/index.jsx
- client/controllers/PlanningController.js
- client/reducers/modal.js
- client/selectors/index.js
- client/styles/index.scss
- index.js
> Planning app outside from the workpsace

- client/views/eventEmailConfig.html
- index.js
- server/planning/__init__.py
- server/planning/feeding_services/event_email_service.py
adds support for email ingest of ntb xml and ics file events.
> Email ingest

- client/actions/planning.js
- client/containers/RemoveAgendaConfirmation.jsx
Also, close the planning editor upon agenda deletion.
> [SDESK-1128] Open planning item in editor when related planning link is clicked while deleting an agenda

- README.md
- index.js
> fix(top-navbar): Removed topTemplateUrl from the root planning activity.

- client/selectors/index.js
Fix a bug in the current filter
> A planning without ending date and with an old coverage due date is old

- .travis.yml
Downloads the latest nvm utility from their github repo
> (fix) Issues with Travis build system and the nvm utility

- client/actions/desks.js
- client/actions/index.js
- client/actions/users.js
- client/components/CoverageAssign/CoverageAssignSelect.jsx
- client/components/CoverageAssign/_test.jsx
- client/components/CoverageAssign/index.jsx
- client/components/CoverageAssign/style.scss
- client/components/SearchBar/index.jsx
- client/components/index.js
- client/containers/Coverage/index.jsx
- client/containers/Coverage/style.scss
- client/controllers/PlanningController.js
- client/reducers/desks.js
- client/reducers/index.js
- client/reducers/users.js
- server/features/coverage.feature
- server/features/planning.feature
- server/planning/coverage.py
Reference UI design:
https://wiki.sourcefabric.org/display/NR/Planning+interface?preview=/24052602/41910540/Planning_Split-view_2.png
and
https://wiki.sourcefabric.org/display/NR/Planning+interface?preview=/24052602/41910541/Planning_Split-view_3.png
> [SDESK-1284] Assignments for coverages

- client/components/EventsList/_test.jsx
- client/components/EventsListContainer/_test.jsx
- client/components/EventsPanelContainer/_test.jsx
- client/components/tests/PlanningApp_test.jsx
- client/selectors/index.js
- client/selectors/tests/index_test.js
fix is only applied to initial state of the event list without a search applied.
> fix(client): SDESK-1342: Events list: show "today" as the first day in the list

- client/components/AgendaItem/_test.jsx
- client/components/AgendaItem/index.jsx
- client/components/EventForm/index.jsx
- client/components/EventsListContainer/index.jsx
- client/components/EventsListContainer/style.scss
- client/components/ManageAgendasModalContainer/index.jsx
- client/components/PlanningPanelContainer/index.jsx
- client/components/PlanningPanelContainer/style.scss
- client/styles/index.scss
> SDESK-1415 (fix): Manage Agendas modal

- client/components/AgendaItem/index.jsx
- small fix, remove redundant title
> Agenta item fix

- client/actions/planning.js
- client/actions/tests/agenda_test.js
- client/actions/tests/events_test.js
- client/actions/tests/planning_test.js
- client/actions/tests/privileges_test.js
- client/components/CoverageAssign/_test.jsx
- client/components/DueDate/_test.jsx
- client/components/EditPlanningPanelContainer/_test.jsx
- client/components/EventsList/_test.jsx
- client/components/EventsPanelContainer/_test.jsx
- client/components/PlanningPanelContainer/_test.jsx
- client/components/SelectAgenda/_test.jsx
- client/components/fields/tests/DatePicker_test.jsx
- client/components/fields/tests/DayOfWeek_test.jsx
- client/components/fields/tests/DayPickerInput_test.jsx
- client/components/fields/tests/SelectMetaTermsField_test.jsx
- client/components/fields/tests/TimePicker_test.jsx
> fix(tests): Action tests with promises not catching errors

- server/data/vocabularies.json
> [DATA] [VOCABULARY] added Coverage Statuses

- client/components/EditPlanningPanelContainer/style.scss
- client/components/EventForm/index.jsx
- client/components/EventForm/style.scss
- client/components/EventsList/index.jsx
- client/components/ListItem/index.jsx
- client/components/ListItem/style.scss
- client/components/PlanningPanelContainer/index.jsx
- client/components/PlanningPanelContainer/style.scss
- client/components/PubStatusLabel/index.jsx
- client/styles/index.scss
> Planning UI

- client/actions/agenda.js
- client/actions/tests/agenda_test.js
- client/components/MultiEventsSelectionActions/index.jsx
- client/controllers/PlanningController.js
Display better notification when a user try to create a planning from an event if there is no agenda selected
SDESK-1589
> Notification on AddEventToCurrentAgenda

- client/actions/agenda.js
- client/actions/tests/agenda_test.js
- client/components/PlanningForm/index.jsx
> Adds description to planning form

- client/actions/events.js
- client/components/EventForm/index.jsx
> Event publishing has a better informative message

- client/actions/events.js
- client/components/EventForm/index.jsx
- client/components/EventItem/index.jsx
- client/components/PubStatusLabel/index.jsx
- client/constants/events.js
- server/data/vocabularies.json
- server/features/events.feature
- server/features/publish.feature
- server/features/steps/steps.py
- server/planning/__init__.py
- server/planning/events.py
- server/planning/events_history.py
- server/planning/events_publish.py
- server/planning/output_formatters/__init__.py
- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb.xml
- server/planning/tests/output_formatters/ntb_test.py
- server/requirements.txt
on publish put events into publish queue and let superdesk to transmit it
SDESK-60
requires https://github.com/superdesk/superdesk-core/pull/983
> feat(publish): publish events

- client/actions/locations.js
- server/planning/events.py
- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb_test.py
and output it in ntb event format
SDESK-60
> feat(events): store event location as geo point in elastic

- server/features/coverage.feature
- server/features/planning.feature
- server/planning/coverage.py
depends on 
https://github.com/superdesk/superdesk-core/pull/988
https://github.com/superdesk/superdesk-client-core/pull/1733
> Adds an activity when a covergage is updated

- server/planning/locations.py
An error was thrown when we try to save with some location suggestions
> Allow empty location title SDESK-1645

- client/components/EventsPanelContainer/style.scss
- client/components/PlanningItem/index.jsx
- client/components/PlanningPanelContainer/index.jsx
- client/components/PlanningPanelContainer/style.scss
- client/components/SearchBar/style.scss
- client/styles/index.scss
- fix for streching event panel subnav
- agenda top bar, items list
> UI improvements

- client/actions/events.js
- client/actions/events/ui.js
- client/components/EventForm/index.jsx
- server/features/events.feature
- server/features/events_recurring.feature
- server/features/publish.feature
- server/planning/events_publish.py
publish must run only after locking otherwise
it won't persist changes to event state
also added pubstatus to publish call so there is no need to set it first
SDESK-1620
> fix(events): fix save and publish

- server/features/events_recurring.feature
- server/planning/events.py
[SDESK-1726] After turning a single event into a series the upcoming events appear locked
> [SDESK-1725] After changing an event to appear in series that event itself is not included in the series

- client/actions/planning/api.js
- client/actions/planning/notifications.js
- client/actions/planning/tests/api_test.js
- client/actions/planning/tests/notifications_test.js
- client/actions/planning/tests/ui_test.js
- client/actions/planning/ui.js
- client/components/EditPlanningPanelContainer/index.jsx
- client/components/EditPlanningPanelContainer/style.scss
- client/components/PlanningForm/_test.jsx
- client/components/PlanningForm/index.jsx
- client/components/PlanningHistoryList/index.jsx
- client/components/PlanningItem/index.jsx
- client/constants/index.js
- client/utils/index.js
- client/utils/planning.js
- server/features/events_spike.feature
- server/features/planning_publish.feature
- server/features/planning_spike.feature
- server/planning/__init__.py
- server/planning/common.py
- server/planning/planning.py
- server/planning/planning_publish.py
- server/planning/planning_spike.py
[SDESK-1663] Implement placeholder endpoint for publishing a Planning item (TBD)
> [SDESK-1663] As an editor I want to be able to determine whether a Planning Item is publicly available

- client/components/ItemActionsMenu/index.jsx
- client/utils/events.js
> [SDESK-1845] Cancelled event cannot be duplicated

- client/actions/events/notifications.js
- client/components/Coverage/_test.jsx
- client/components/Coverage/index.jsx
- client/components/EventForm/_test.jsx
- client/components/EventForm/index.jsx
- client/components/EventForm/style.scss
- client/components/EventItem/_test.jsx
- client/components/ItemActionsMenu/_test.jsx
- client/components/ItemActionsMenu/index.jsx
- client/components/PlanningForm/index.jsx
- client/components/fields/style.scss
- client/styles/index.scss
- client/utils/events.js
- server/planning/item_lock.py
- server/planning/planning_types.py
1) lock_action passed in push notifications 
2) History pane close button made darker for visibility 
3) Close button added to Item Actions menu
> [SDESK-1792] Replace 'description' with 'ednote' in Coverage and Planning form and other adhoc fixes

- client/components/AssignmentList/style.scss
- client/components/AssignmentListContainer/style.scss
- client/components/AssignmentListSearchHeader/index.jsx
- added div block for element with badge in UI framework
- implementation of the above in assignments subnav (button with badge)
> Assignments subnav UI improvements

- client/actions/planning/api.js
- client/actions/planning/ui.js
- client/components/EventsListContainer/style.scss
- client/components/MultiEventsSelectionActions/index.jsx
- client/components/MultiSelectionActions/index.jsx
- client/components/MultiSelectionActions/style.scss
- client/components/PlanningItem/index.jsx
- client/components/PlanningList/index.jsx
- client/components/PlanningPanelContainer/index.jsx
- client/constants/planning.js
- client/reducers/index.js
- client/reducers/planning.js
- client/reducers/tests/planning_test.js
- client/selectors/index.js
- client/services/PlanningStoreService.js
- client/utils/_test.js
- client/utils/index.js
- index.js
- server/features/planning_export.feature
- server/planning/__init__.py
- server/planning/planning_export.py
it allows user to select planning items and run export
SDESK-301 SDESK-1863 SDESK-1864
> feat(export): add export planning items as article

- client/actions/planning/api.js
- client/components/SortItemsModal/index.jsx
- client/components/SortItemsModal/style.scss
- client/services/PlanningStoreService.js
- filter out locked items and items marked not for publication
- add open button to notification which takes you to editor
- style sortable modal
SDESK-1907 SDESK-1908 SDESK-1909
> feat(export): tweak export planning items

- client/actions/events.js
- client/actions/events/api.js
- client/actions/events/notifications.js
- client/actions/events/tests/api_test.js
- client/actions/events/tests/notifications_test.js
- client/actions/events/tests/ui_test.js
- client/actions/events/ui.js
- client/components/EventActionConfirmation/forms/convertToRecurringEventForm.jsx
- client/components/EventActionConfirmation/forms/updateRecurringEventsForm.jsx
- client/components/EventActionConfirmation/forms/updateTimeForm.jsx
- client/components/EventForm/index.jsx
- client/constants/events.js
- client/reducers/events.js
- client/reducers/tests/events_test.js
- client/utils/testUtils.js
- server/features/events.feature
- server/planning/events_publish.py
Remove 'Publish' action when creating a new Event
Use websocket notifications when publishing/unpublishing Events
> [SDESK-1566] Add option to publish series of recurring events.

- client/actions/planning/api.js
- client/services/PlanningStoreService.js
> fix(export): don't export items locked by current user

- .eslintrc.js
- client/components/EventScheduleForm/index.jsx
- client/components/ItemActionConfirmation/forms/convertToRecurringEventForm.jsx
- client/components/ItemActionConfirmation/forms/rescheduleEventForm.jsx
- client/components/ItemActionConfirmation/modal.jsx
- client/components/RepeatEventForm.jsx
- client/constants/index.js
Disable eslint rule for jasmine/new-line-before-expect
> [SDESK-1945] Save and reschedule buttons appear activated although no changes are made

- package.json
- server/features/assignments_content.feature
- server/planning/__init__.py
- server/planning/assignments_content.py
- server/planning/delivery.py
- server/requirements.txt
also covers part of [SDESK-96]
Depends on https://github.com/superdesk/superdesk-core/pull/1046
> [SDESK-1998] Create content from assignment.

- server/planning/__init__.py
- server/planning/assignments.py
- server/planning/planning_notifications.py
- server/planning/planning_notifications_test.py
> [SDESK-2035] Add Slack notifications

- client/components/AssignmentItem/_test.jsx
- client/components/AssignmentPreviewContainer/_test.jsx
- client/components/EventForm/_test.jsx
- client/components/EventItem/_test.jsx
- client/components/ItemActionsMenu/ActionsMenu.jsx
- client/components/ItemActionsMenu/_test.jsx
- client/components/ItemActionsMenu/index.jsx
- client/components/PlanningForm/_test.jsx
- client/components/PlanningItem/_test.jsx
- client/components/tests/helpers/actionMenu.js
- package.json
- webpack.config.js
Depends on: https://github.com/superdesk/superdesk-client-core/pull/1933
> [SDESK-2149] Item Actions Menu to display properly in Assignments List

- client/components/AssignmentPreviewContainer/style.scss
- client/controllers/AssignmentPreviewController.js
- client/controllers/index.js
- client/index.js
- package.json
Assignment tab for the monitoring preview.
> [SDESK-2086] Adding assignment tab to monitoring item preview.

- client/actions/planning/ui.js
- client/components/AssignmentItem/index.jsx
- client/components/AssignmentPreviewContainer/index.jsx
- client/constants/assignments.js
- client/constants/planning.js
- client/utils/assignments.js
- client/utils/index.js
- server/features/assignments_complete.feature
- server/planning/assignments/assignments_complete.py
> [SDESK-2237] Confirm Availability action for non-text assignments

- client/components/AbsoluteDate/index.jsx
- client/components/Assignments/AssignmentEditor/index.jsx
- client/components/Assignments/AssignmentPopup/index.jsx
- client/components/ItemActionConfirmation/forms/editPriorityForm.jsx
- client/components/ItemActionConfirmation/index.jsx
- client/components/ItemActionConfirmation/modal.jsx
- client/components/ItemActionConfirmation/style.scss
- client/components/ModalWithForm/index.jsx
- client/components/Planning/PlanningPreviewContent.jsx
- client/components/UI/Form/ColouredValueInput/index.jsx
- client/components/UI/Form/ColouredValueInput/style.scss
- client/components/UI/Form/LineInput.jsx
- client/components/UI/Form/TextInput.jsx
- client/components/UI/style.scss
- client/validators/assignments.jsx
- client/validators/index.js
- client/validators/profile.js
* Remove redux-forms from ModalWithForm
* Validation in the AssignmentEditor
> [SDESK-2352] Assignment Actions ported to the new UI design

- client/actions/assignments/notifications.js
- client/actions/assignments/tests/ui_test.js
- client/actions/assignments/ui.js
- client/components/Assignments/AssignmentEditor/index.jsx
- client/components/Coverages/CoverageEditor/CoverageForm.jsx
- client/components/Coverages/CoverageEditor/CoverageFormHeader.jsx
- client/components/Coverages/CoverageItem.jsx
- client/components/Coverages/CoveragePreview.jsx
- client/components/ItemActionConfirmation/forms/editPriorityForm.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/UI/Form/Select.jsx
- server/features/assignments.feature
- server/planning/assignments/assignments.py
- server/planning/assignments/assignments_complete.py
[SDESK-2385] Fixing the error when tries to open content from the assignment.
[SDESK-2386] Default value for Assignment Priority should be medium.
> [SDESK-2385][SDESK-2068](fix): Change management for planning/coverage after assignment is created.

- client/components/Main/ItemEditor/Editor.jsx
- client/utils/index.js
- client/utils/testUtils.js
- package.json
Polyfill Promise.finally for older browsers
> (fix) Clicking 'Create' on the Editor sent two POST requests

- client/components/Coverages/CoverageArrayInput.jsx
- client/components/Coverages/CoverageEditor/CoverageFormHeader.jsx
- client/components/Coverages/CoverageEditor/index.jsx
- client/components/Coverages/CoverageItem.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/StateLabel/index.jsx
- client/constants/coverages.js
- client/constants/index.js
- client/utils/index.js
- client/utils/planning.js
- server/features/assignments.feature
- server/features/assignments_link.feature
- server/features/content_rewrite.feature
- server/planning/assignments/assignments.py
- server/planning/common.py
- server/planning/planning/planning.py
- server/planning/planning/planning_postpone.py
- server/planning/planning/planning_reschedule.py
- server/planning/planning/planning_spike.py
- server/planning/planning/planning_tests.py
- server/planning/planning_notifications.py
Does not cover draft-assignment delete or purge activities on planning item spike or coverage cancellation.
> [SDESK-2458][SDESK-2459][SDESK-2460] Create draft assignments and add-to-workflow action on Coverage

- client/components/Events/EventScheduleInput/_test.jsx
- client/components/Events/EventScheduleInput/index.jsx
- client/components/ItemActionConfirmation/forms/rescheduleEventForm.jsx
- server/planning/planning/planning_types.py
* Use the formProfile 'events.dates.schema.defaultDurationOnChange' to control default length of the Event when changing the start/end times
> [SDESK-2498] Notify the user if the 'Reschedule' action will result in a multi-day event

- client/actions/agenda.js
- client/actions/planning/api.js
- client/actions/planning/tests/api_test.js
- client/actions/tests/agenda_test.js
- client/components/Agendas/AgendaNameList.jsx
- client/components/Agendas/index.jsx
- client/components/AssignmentPreviewContainer/PlanningPreview.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/InternalNoteLabel/index.jsx
- client/components/ItemActionConfirmation/forms/updateRecurringEventsForm.jsx
- client/components/ItemActionConfirmation/forms/updateTimeForm.jsx
- client/components/ItemActionConfirmation/tests/updateRecurringEventsForm_test.jsx
- client/components/LockContainer/index.jsx
- client/components/Main/AgendaSubnavDropdown.jsx
- client/components/Main/FiltersBar.jsx
- client/components/Main/FiltersBox.jsx
- client/components/Main/ItemEditor/EditorItemActions.jsx
- client/components/Main/style.scss
- client/components/Main/tests/FiltersBox_test.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/Planning/PlanningItem.jsx
- client/components/Planning/PlanningPreviewContent.jsx
- client/components/UI/Preview/Row.jsx
- client/components/UI/SubNav/Dropdown.jsx
- client/components/UI/SubNav/style.scss
- client/planning.js
- client/utils/planning.js
[SDESK-2466]
[SDESK-2485]
[SDESK-2486]
> [SDESK-2517](fix): Agenda as a filter not a context.

- client/actions/events/api.js
- client/actions/events/notifications.js
- client/actions/events/tests/api_test.js
- client/actions/events/tests/notifications_test.js
- client/actions/events/tests/ui_test.js
- client/actions/events/ui.js
- client/components/Events/EventHistory.jsx
- client/components/Events/EventItem.jsx
- client/components/Events/RecurringRulesInput/EndsInput.jsx
- client/components/ItemActionConfirmation/forms/convertToRecurringEventForm.jsx
- client/components/ItemActionConfirmation/forms/rescheduleEventForm.jsx
- client/components/ItemActionConfirmation/forms/updateEventRepetitions.jsx
- client/components/ItemActionConfirmation/forms/updateTimeForm.jsx
- client/components/ItemActionConfirmation/index.jsx
- client/components/ItemActionConfirmation/modal.jsx
- client/components/Main/ListGroupItem.jsx
- client/components/UI/Button.jsx
- client/constants/events.js
- client/planning.js
- client/utils/events.js
- server/features/events_update_repetitions.feature
- server/planning/events/__init__.py
- server/planning/events/events_base_service.py
- server/planning/events/events_cancel.py
- server/planning/events/events_history.py
- server/planning/events/events_reschedule.py
- server/planning/events/events_update_repetitions.py
* (fix) UI.Button clickable if disabled=true
> [SDESK-2446] New Event action 'Update Repetitions'

- Gruntfile.js
- po/planning.pot
usage: `grunt gettext:extract`
> configure gettext:extract task

- client/actions/events/api.js
- client/actions/events/tests/api_test.js
- client/actions/events/ui.js
- client/actions/planning/tests/api_test.js
- client/components/EventHistoryList/index.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/Events/tests/EventPreviewContent_test.jsx
- client/components/Main/ItemEditor/EditorHeader.jsx
- client/components/Main/ItemEditorModal/index.jsx
- client/components/PlanningHistoryList/index.jsx
- client/components/UI/Form/FileInput.jsx
- client/components/UI/Form/TextAreaInput.jsx
- client/components/UI/Form/style.scss
- client/components/UI/style.scss
Needs https://github.com/superdesk/superdesk-client-core/pull/2253
> [SDESK-2622] File Input refactor

- client/actions/planning/api.js
- server/planning/planning/planning_export.py
and fix missing notification on success.
SDNTB-487 SDESK-2900
> fix(export): add name to export as article

- README.md
Check if suggested client configuration works for you.
> Add missing client configurations

- client/components/Assignments/AssignmentItem/index.jsx
- server/features/assignments.feature
- server/features/assignments_content.feature
- server/planning/assignments/assignments.py
- server/planning/assignments/assignments_content.py
- server/planning/planning/planning.py
* Also provide the ability to search assignments for this description
> [SDESK-2871] Show description in Assignment list

- client/components/AdvancedSearch/index.jsx
- client/components/Assignments/AssignmentPreviewContainer/AssignmentPreview.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/Events/tests/EventPreviewContent_test.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/Planning/PlanningPreviewContent.jsx
- client/components/UI/Form/Field.jsx
- client/components/UI/Form/SelectMetaTermsInput/index.jsx
- client/reducers/index.js
- client/services/PlanningStoreService.js
- use `ANPA Category` label to be consistent with superdesk
- set scheme for custom subject so it will show up there in authoring
SDNTB-492
> fix(cvs): fix custom cvs for ntb

- server/planning/feeding_services/event_email_service.py
- server/planning/feeding_services/event_file_service.py
- server/planning/feeding_services/event_http_service.py
Changes for the core's feeding services labels are in https://github.com/superdesk/superdesk-core/pull/1302
> [INGEST] Change feed service labels to fit common naming style

- client/components/CustomVocabulariesFields.jsx
- client/components/CustomVocabulariesPreview.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/Planning/PlanningPreviewContent.jsx
- client/utils/testUtils.js
> fix(events): sync custom cvs handling with planning items

- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb_test.py
- use subject with scheme category for category field
SDNTB-497
> fix(publish): handle custom cvs in ntb event output

- client/components/Agendas/AgendaItem.jsx
- client/components/Agendas/AgendaList.jsx
- client/components/Agendas/EditAgenda.jsx
- client/components/Assignments/AssignmentGroupList.jsx
- client/components/Assignments/AssignmentPreviewContainer/EventPreview.jsx
- client/components/Events/EventDateTime.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventItem.jsx
- client/components/Events/EventItemWithPlanning.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/Events/RecurringRulesInput/RepeatsEveryInput.jsx
- client/components/Events/RecurringRulesInput/RepeatsInput.jsx
- client/components/Events/tests/EventPreviewContent_test.jsx
- client/components/GeoLookupInput/AddGeoLookupResultsPopUp.jsx
- client/components/ItemActionsMenu/ActionsMenuPopup.jsx
- client/components/Main/ListPanel.jsx
- client/components/MultiSelectActions.jsx
- client/components/Planning/PlanningItem.jsx
- client/components/UI/Form/DateInput/DayPicker.jsx
- client/components/UI/Form/DateInput/index.jsx
- client/components/UI/Form/FileInput.jsx
- client/components/UI/Form/LinkInput.jsx
- client/components/UI/Form/TimeInput/index.jsx
- client/components/UI/SearchBar/index.jsx
- client/constants/assignments.js
> fix(gettext): fix missing translations

- server/features/events.feature
- server/features/planning.feature
- server/planning/events/events.py
- server/planning/planning/planning.py
> populate firstcreated and versioncreated in events/planning

- client/components/UI/Form/DateInput/DayPicker.jsx
> fix(ui): use config for first week day in day picker

- client/components/Agendas/AgendaList.jsx
- client/components/Assignments/AssignmentGroupList.jsx
- client/components/AuditInformation/index.jsx
- client/components/Events/EventItem.jsx
- client/components/MultiSelectActions.jsx
- client/components/OrderBar/index.jsx
- client/components/StateLabel/index.jsx
- client/components/UI/SearchField/index.jsx
- client/utils/index.js
- client/validators/profile.js
> fix(gettext): add missing gettext

- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb_test.py
> fix(ntb-event): handle canceled/postponed events like unpost

- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb_test.py
> fix(ntb-event): fix formatting for nifs ingested dates

- client/controllers/AddToPlanningController.js
- client/controllers/AddToPlanningController_test.js
- client/controllers/AssignmentController.js
- client/controllers/AssignmentPreviewController.js
- client/controllers/FulfilAssignmentController.js
- client/controllers/PlanningController.js
- client/services/PlanningStoreService.js
- client/spec/helpers/form/coverageList.js
- client/spec/helpers/utils.js
- client/views/assignment.html
- client/views/planning.html
* Make sure there is only 1 Redux store created
> [SDESK-3068] (fix) Improve the way the Planning controllers are loaded

- server/features/planning.feature
- server/planning/planning/planning.py
- server/planning/planning/planning_types.py
when creating planning item for an event.
> fix(planning): populate headline using event name

- client/components/GeoLookupInput/AddGeoLookupInput.jsx
- client/utils/index.js
- server/planning/locations.py
we need it for map display with reasonable zoom level
> add boundingbox to event locations

- client/actions/assignments/ui.js
- client/actions/main.js
- client/actions/tests/main_test.js
- client/components/Events/EventMetadata/index.jsx
- client/reducers/planning.js
- client/reducers/tests/planning_test.js
- client/selectors/main.js
- server/planning/events/events.py
- server/planning/planning/planning.py
- server/planning/planning/planning_history.py
[SDESK-3109] 
[SDESK-3150] 
[SDESK-3151] 
[SDESK-3136]
> (fix): Fixing UI issues related to assignments and events.

- server/planning/output_formatters/json_planning.py
we need all coverages in newsroom
> add all coverages to planning json output

- client/actions/contacts.js
- client/components/Contacts/ContactField.jsx
- client/components/Contacts/ContactMetaData/index.jsx
- client/components/Contacts/SelectSearchContactsField/index.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/Main/EditorPanel.jsx
* Event Contacts input field editable while the form is in read-only state
> [SDESK-3340][SDESK-3341](fix): Event Contacts autosave not being restored

- client/components/Planning/PlanningEditor/index.jsx
Reverts superdesk/superdesk-planning#999
> Revert "[SDESK-3342](fix): Duplicated 'Coverage Cancelled' on internal note and ednote"

- client/components/GeoLookupInput/CreateNewGeoLookup.jsx
- Adding new field City/Town
- Changing the label for State to State/Province/Region
> [SDESK-3440](fix): Improving the location dialog.

- client/components/GeoLookupInput/AddGeoLookupInput.jsx
- client/components/GeoLookupInput/CreateNewGeoLookup.jsx
- client/selectors/general.js
Depends on https://github.com/superdesk/superdesk-core/pull/1382
> [SDESK-3454][SDESK-3468] Use 'region' and 'country' vocabularies in Location and Contacts forms

- client/actions/contacts.js
- client/components/Contacts/ContactInfoContainer/index.jsx
- client/components/Contacts/ContactLabel.jsx
- client/components/Contacts/ContactMetaData/index.jsx
- client/components/Contacts/SelectSearchContactsField/style.scss
- client/utils/index.js
Depends on: https://github.com/superdesk/superdesk-client-core/pull/2603
> [SDESK-3492] Display inactive contacts of an event

- client/components/UI/Form/SelectMetaTermsInput/SelectFieldPopup.jsx
- client/components/UI/Popup/Popup.jsx
https://dev.sourcefabric.org/browse/SDESK-3445
> Improvement for the agenda and calendar search in items

- client/selectors/config.js
https://dev.sourcefabric.org/browse/SDNTB-533
> fixed: Date is shown twice in the Planning events list view

- server/features/steps/steps.py
- server/planning/tests/ingest/ingest_test.py
Depends on https://github.com/superdesk/superdesk-core/pull/1409
> [INGEST][REGISTRY] SDESK-3582 SDESK-3582 Use 'get_feeding_service' factory to get a feeding service instance.

- client/components/Main/FiltersBar.jsx
- client/components/Main/FiltersBox.jsx
- client/components/UI/Form/CheckboxGroup.jsx
- client/components/UI/Form/index.jsx
- client/components/UI/SubNav/SubNav.jsx
SDESK-2780
requires https://github.com/superdesk/superdesk-client-core/pull/2723
> fix navbar UI when there is calendar/agenda dropdown

- client/components/AdvancedSearch/index.jsx
- client/components/Coverages/CoverageArrayInput.jsx
- client/components/Coverages/CoverageEditor/CoverageForm.jsx
- client/components/Coverages/CoverageEditor/index.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventScheduleInput/index.jsx
- client/components/Events/RecurringRulesInput/index.jsx
- client/components/GeoLookupInput/index.jsx
- client/components/ItemActionConfirmation/tests/formValidations_test.jsx
- client/components/Main/ItemEditor/Editor.jsx
- client/components/Main/ItemEditor/EditorHeader.jsx
- client/components/Main/ItemEditorModal/index.jsx
- client/components/Main/ListGroupItem.jsx
- client/components/Main/SearchPanel.jsx
- client/components/Modal/Body.jsx
- client/components/Modal/index.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/UI/Button.jsx
- client/components/UI/Form/DateInput/index.jsx
- client/components/UI/Form/SelectMetaTermsInput/index.jsx
- client/components/UI/Form/TimeInput/index.jsx
- client/components/UI/Form/TimeZoneInput.jsx
* Change string refs to ref callback in ItemEditorModal
> (fix-eslint): Add PropType entry for all props

- client/components/UI/ToggleBox/index.jsx
> make toggle box toggle on enter when focused

- client/index.js
SDESK-3560
Depends on https://github.com/superdesk/superdesk-client-core/pull/2754
> Move menu item creation to planning index

- client/components/CustomVocabulariesFields.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventPreviewContent.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/Planning/PlanningPreviewContent.jsx
- client/services/PlanningStoreService.js
- client/validators/events.js
cv must be enabled via planning type in order to be visible
in editor. also default subject field will be only visible
if enabled.
SDESK-3485
> fix(profiles): handle custom cvs via planning types

- .eslintrc.js
- client/components/PlanningDetailsWidget.tsx
- client/index.js
- client/utils/planning.js
- client/views/planning-details-widget.html
> add planning details authoring widget

- client/utils/gettext.js
- client/utils/index.js
> fix item state not being translated

- client/components/CustomVocabulariesFields.jsx
- client/validators/index.js
- client/validators/tests/validators_test.js
> validate custom fields according to schema

- client/components/Assignments/AssignmentPreviewContainer/EventPreview.jsx
- client/components/Coverages/CoverageItem.jsx
- client/components/Coverages/CoveragePreview.jsx
- client/components/Datetime/index.jsx
- client/components/Events/EventDateTime.jsx
- client/components/Events/EventMetadata/_test.jsx
- client/components/Events/EventMetadata/index.jsx
- client/components/Events/EventScheduleSummary/index.jsx
- client/components/Events/tests/EventPreviewContent_test.jsx
- client/components/Planning/PlanningPreviewContent.jsx
- client/utils/events.js
- client/utils/index.js
- client/utils/time.js
SDESK-4057
SDESK-4058
SDESK-4059
> (fix): Modified display of timezone in events and planning list/preview.

- server/planning/planning/planning_export.py
> add contacts info to export as article template

- client/components/FulFilAssignmentModal/index.jsx
- client/index.js
- client/services/AssignmentsService.js
- client/services/tests/AssignmentsService_test.js
- server/planning/assignments/__init__.py
- Implement checking of config option 'planning_check_for_assignment_on_publish', defaults to false
> [SDESK-4128] Modify onpublish fulfil modal

- server/planning/assignments/assignments.py
> [SDESK-4214] Coverage completion notifications being generated on content updates

- server/planning/planning_article_export.py
SDBELGA-110
Send an array of agendas to be rendered on templates. Required by https://github.com/superdesk/superdesk-belga/pull/44
> Send agendas to export templates

- server/planning/planning_article_export.py
> [SDBELGA-120] Remove disabled agendas from export

- server/features/events_template.feature
- server/planning/events/__init__.py
- server/planning/events/events.py
- server/planning/events/events_schema.py
- server/planning/events/events_template.py
Requests examples (no headers):
- List templates
```
curl -X GET http://localhost:5000/api/events_template
```
- Create template
```
curl -X POST http://localhost:5000/api/events_template \
-d '{
"template_name": "some name",
"based_on_event": "_event_id_"
}'
```
- Get recent templates
```
curl -X GET 'http://localhost:5000/api/recent_events_template?limit=3' 
```
> SDBELGA-108 Event templates API.

- server/planning/assignments/assignments.py
- server/planning/assignments/assignments_link.py
- server/planning/assignments/delivery.py
> [SDESK-4451] sequence_no in delivery record was null instead of 0 by default

- server/planning/planning_article_export.py
SDBELGA-129
Needed for https://github.com/superdesk/superdesk-belga/pull/51
> Convert agenda IDs to objects so they can be used in templates

- server/planning/planning_article_export.py
SDBELGA-129
Needed for https://github.com/superdesk/superdesk-belga/pull/56
> Include coverage without users on export templates

- client/actions/planning/api.js
- client/actions/planning/featuredPlanning.js
- client/actions/planning/tests/featuredPlanning_test.js
- client/components/Planning/FeaturedPlanning/FeaturedPlanningItem.jsx
- client/components/Planning/PlanningDateTime.jsx
- client/selectors/featuredPlanning.js
- client/utils/planning.js
- server/planning/history.py
- server/planning/output_formatters/json_planning.py
- server/planning/planning/planning.py
- server/planning/planning/planning_duplicate.py
> [SDESK-4562] Logically constrain the scheduling of planned updates to a coverage

- .gitignore
- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb_test.py
> When duplicated event is rescheduled and posted, SD sends file with NTBID of orginal event

- client/index.js
- server/planning/__init__.py
> Introduce configuration for the main left hand side toolbar

- .travis.yml
- client/services/tests/AssignmentsService_test.js
- package.json
- scripts/install_run_unit.sh
- server/requirements.txt
- superdesk.config.js
* Disable compiling extensions when installing superdesk-core into superdesk-planning
> (fix) Place superdesk-core in peerDependencies and update Typescript version

- client/actions/users.js
- client/components/Coverages/CoverageAddAdvancedModal.jsx
- client/components/Coverages/CoverageAddButton/CoveragesMenuPopup.jsx
- client/components/Coverages/CoverageAddButton/index.jsx
- client/components/Coverages/CoverageArrayInput.jsx
- client/components/Planning/PlanningEditor/index.jsx
- client/components/UI/Form/Select.jsx
- client/components/UI/Form/SelectInput.jsx
- client/components/UI/Form/SelectUserInput/index.jsx
- client/constants/coverages.js
- client/selectors/general.js
- client/services/PlanningStoreService.js
- server/planning/__init__.py
allows to quickly define multiple coverages
SDBELGA-148
> implement add coverages advanced modal

- client/components/Coverages/CoverageAddAdvancedModal.jsx
> fix coverage duplication in advanced mode

- client/components/Coverages/CoverageAddAdvancedModal.jsx
it must have a desk if user is selected
SDBELGA-220
> validate coverage in add advanced modal

- client/components/Assignments/AssignmentItem/index.jsx
- client/styles/index.scss
- client/utils/assignments.js
- server/features/events_reschedule.feature
* Add icon-ingest icon to Assignment item in the list view
> [SDESK-4766] Remove 'Start Working' for external coverages

- client/index.js
- client/services/AssignmentsService.js
- client/utils/index.js
- e2e/package.json
- e2e/server/requirements.txt
- server/planning/assignments/__init__.py
Requires https://github.com/superdesk/superdesk-client-core/pull/3337
> [SDESK-4903] (1.10) Show FulfilAssignment challenge on archive send

- client/components/WorkqueueContainer/WorkqueueItem.jsx
- client/components/WorkqueueContainer/index.jsx
- e2e/cypress/support/common/ui/workqueue.js
Depends on: https://github.com/superdesk/superdesk-client-core/pull/3376
> fix(bottom-bar): Refactored bottom-bar structure

- client/apps/Assignments/AssignmentPreview.jsx
- client/components/Locations/LocationsEditor.jsx
- client/components/Main/ItemEditor/Editor.jsx
- client/components/Main/ItemPreview/PreviewPanel.jsx
- client/components/Main/SearchPanel.jsx
- client/components/UI/SidePanel/SidePanel.jsx
- client/controllers/AssignmentPreviewController.js
Depends on https://github.com/superdesk/superdesk-client-core/pull/3446
> [SDESK-5199] Force white background for forms and previews

- server/planning/events/events.py
Depends on PR https://github.com/superdesk/superdesk-core/pull/1868
> fix: import resolve_default_values from apps.archive.common

- server/planning/events/events.py
- server/planning/feed_parsers/ics_2_0.py
Also fixed parsing RRULE attributes
> [SDESK-5654] fix(ingest): ICS failure due to Eve changes

- setup.py
According to the changelog, here are not so many breaking changes that will affect us.
🚚 It would be great to port it to 1.33.*
> Use icalendar>=4.0.3,<4.1

- client/components/EventsPlanningFilters/EditFilterSchedule.tsx
- client/components/fields/editor/ContentTemplate.tsx
- client/services/PlanningStoreService.ts
Increase page size to 200 when getting content filters
> [SDCP-479] fix(filters): Filter schedule templates by desk

- client/api/ui/list.ts
- client/utils/search.ts
- e2e/package.json
- e2e/server/requirements.txt
This has been backported from https://github.com/superdesk/superdesk-planning/pull/1555
> [SDESK-5827] fix: Search panel params not persisting

- .github/workflows/ci-client.yml
- .github/workflows/ci-e2e.yml
- .github/workflows/ci-server.yml
- e2e/package.json
- server/planning/tests/output_formatters/json_event_test.py
Run tests against Python 3.6/3.8 and NodeJS 12.x/14.x
> [SDESK-5831] fix(unit_tests): Update contact_state in tests

- client/api/locations.ts
- client/components/Coverages/CoverageEditor/CoverageForm.tsx
- client/components/Coverages/CoverageEditor/index.tsx
- client/components/Events/EventEditor/index.tsx
- client/components/GeoLookupInput/AddGeoLookupInput.tsx
- client/components/GeoLookupInput/AddGeoLookupInput_test.tsx
- client/components/GeoLookupInput/index.tsx
- client/components/Planning/PlanningEditor/index.tsx
- client/interfaces.ts
Also fix pass language to other input fields in Event, Planning & Coverage editors
> [SDCP-534] Pass Item or Profile language to OpenStreetMaps

- client/components/UI/Form/TimeInput/index.tsx
> translations - missing gettext definition

- server/planning/feeding_services/event_file_service.py
getattr would raise AttributeError so check via hasattr
> fix file ingest when there is no parse_file method

- client/actions/main.ts
- client/components/Events/EventItem.tsx
- client/components/Main/ItemPreview/PreviewPanel.tsx
- client/components/Main/ListGroup.tsx
- client/components/Main/ListPanel.tsx
- client/components/Planning/PlanningItem.tsx
- client/components/UI/Form/LinkInput.tsx
- client/components/UI/Form/style.scss
- client/components/UI/IconButton.tsx
- client/components/UI/SidePanel/Content.tsx
- client/components/UI/SidePanel/Header.tsx
- client/components/fields/editor/EndDateTime.tsx
- client/components/fields/editor/EventLinks.tsx
- client/components/fields/editor/EventSchedule.tsx
- client/components/fields/editor/StartDateTime.tsx
- client/constants/events.ts
- client/constants/planning.ts
- client/utils/events.ts
- client/utils/planning.ts
- e2e/cypress/integration/events/event_action_cancel.spec.ts
- e2e/cypress/integration/events/event_bookmarks.spec.ts
- e2e/cypress/integration/planning/accessibility.spec.ts
- e2e/cypress/support/planning/events/linkInput.ts
- e2e/cypress/support/planning/planningList.ts
> [SDCP-526] fix: Accessibility improvements for preview

- e2e/cypress/integration/planning/accessibility.spec.ts
- e2e/cypress/support/utils/time.ts
> [SDCP-545] add e2e test - returns focus to the list item after preview is closed

- server/planning/data_updates/00032_20210630-161620_roles.py
This new privilege name is defined in this other PR https://github.com/superdesk/superdesk-planning/pull/1627
> [SDBELGA-545] chore(data-update): Add `planning_global_filers` privilege to roles

- client/utils/planning.ts
DEPENDS ON: https://github.com/superdesk/superdesk-ui-framework/pull/565
> SDESK-6090 implement disabled items in accessible menu

- client/actions/assignments/api.ts
- client/actions/events/tests/api_test.ts
- client/actions/planning/featuredPlanning.ts
- client/actions/planning/tests/featuredPlanning_test.ts
- client/components/Events/tests/EventPreviewContent_test.tsx
- client/components/ItemActionConfirmation/forms/convertToRecurringEventForm.tsx
- client/components/ItemActionConfirmation/forms/rescheduleEventForm.tsx
- client/components/ItemActionConfirmation/forms/updateTimeForm.tsx
- client/components/Main/ItemEditor/tests/ItemManager_test.ts
- client/components/Planning/FeaturedPlanning/FeaturedPlanningModal.tsx
- client/config.ts
- client/selectors/featuredPlanning.ts
- client/services/AssignmentsService.tsx
- client/tests.ts
- client/utils/testData.ts
- client/utils/testUtils.ts
- e2e/superdesk.config.js
SDESK-6073
uses https://github.com/superdesk/superdesk-core/pull/2242 https://github.com/superdesk/superdesk-client-core/pull/3949
> use server config for default timezone

- server/planning/output_formatters/__init__.py
- server/planning/output_formatters/file_providers.py
- server/planning/output_formatters/json_event.py
- server/planning/tests/output_formatters/file_providers_test.py
- server/planning/tests/output_formatters/json_event_test.py
Requires https://github.com/superdesk/superdesk-core/pull/2254
> [SDESK-6121] Move file publishing from json formatter to registered callback

- server/features/assignments.feature
- server/features/assignments_link.feature
- server/features/assignments_planning_publish.feature
- server/features/content_rewrite.feature
- server/features/events_cancel.feature
- server/features/events_postpone.feature
- server/features/events_recurring.feature
- server/features/events_reschedule.feature
- server/features/events_update_time.feature
- server/features/planning_cancel.feature
- server/features/planning_featured_post.feature
- server/features/planning_post.feature
- server/features/publish.feature
Caused by the changes from https://github.com/superdesk/superdesk-core/pull/2266
> [SDESK-6178] fix(behave): Add is_active when creating subscribers

- client/components/fields/editor/EventAttachments.tsx
- client/components/fields/editor/EventLinks.tsx
- client/components/fields/editor/index.tsx
- client/components/fields/resources/common.ts
- client/components/fields/resources/events.ts
- e2e/server/settings.py
- server/features/content_profiles_event.feature
- server/planning/content_profiles/profiles/event.py
> SDESK-6173 fix: Redundant attachment section when adding attachment field in planning profile

- server/planning/planning_article_export.py
This PR is to support our routine Sports Outlook and also for the Olympics.
> Add assignment sluglines and assignee details to outlook export

- client/validators/index.ts
This fix is not required in 2.4.0+ as it is already fixed there
> [SDESK-6346] fix: Skip field validation if schema is null

- .fireq.json
- client/utils/search.ts
- e2e/index.js
- e2e/package.json
- e2e/server/requirements.txt
- package.json
- server/requirements.txt
Cherry-picked from v2.3.0 release
> [SDESK-6047] fix(search): Agenda filter not working from subnav (#1613)

- client/components/Coverages/CoverageEditor/CoverageForm.tsx
> fix coverage file attachments

- client/components/Main/ListPanel.tsx
- client/components/UI/Form/SelectMetaTermsInput/index.tsx
- client/components/UI/Form/SelectMetaTermsInput/style.scss
- client/components/UI/style.scss
- client/components/WorkqueueContainer/WorkqueueItem.tsx
- client/components/WorkqueueContainer/index.tsx
> Planning accessibility feb2022

- e2e/cypress/integration/events/event_action_create_planning.spec.ts
To get around daylight saving changes
> fix(e2e): Calculate Planning datetime from Event datetime

- client/components/ItemActionConfirmation/forms/rescheduleEventForm.tsx
so it can be translated later.
CPNHUB-79
> avoid `Event Rescheduled` in the payload

- .github/workflows/ci-client.yml
- .github/workflows/ci-e2e.yml
- README.md
- package.json
- scripts/ci-install.sh
See https://github.com/cheeriojs/cheerio/issues/2545
Also fixes slow npm installs with `git config --global url."https://git@".insteadOf git://`
> fix(ci): Lock cheerio version to 1.0.0-rc10

- client/components/EventsPlanningFilters/EditFilter.tsx
When changing params the SAVE button isnt getting enabled
> fix(ui): Calculating dirty state in Filter form

- client/components/fields/index.tsx
- client/components/fields/preview/index.ts
- client/components/fields/resources/events.ts
- client/interfaces.ts
- client/utils/contentProfiles.ts
- server/planning/content_profiles/profiles/event.py
- server/planning/content_profiles/utils.py
- server/planning/events/events_schema.py
- server/planning/feed_parsers/events_ml.py
- server/planning/feed_parsers/events_ml_test.py
- server/planning/feed_parsers/fixtures/events_ml_259625.xml
Depends on https://github.com/superdesk/superdesk-core/pull/2383
> [STTNHUB-179] ingest(eventsml): Fix date parsing and add new Event fields

- client/actions/events/notifications.ts
- client/actions/events/tests/notifications_test.ts
- client/actions/main.ts
- client/actions/planning/notifications.ts
- client/actions/planning/tests/notifications_test.ts
- client/interfaces.ts
- server/planning/common.py
- server/planning/events/events.py
- server/planning/events/events_schema.py
- server/planning/feed_parsers/events_ml.py
- server/planning/feed_parsers/events_ml_test.py
- server/planning/feed_parsers/ics_2_0.py
- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/superdesk_event_json.py
- server/planning/feed_parsers/superdesk_planning_xml.py
- server/planning/feed_parsers/superdesk_planning_xml_test.py
- server/planning/planning/planning.py
Depends on https://github.com/superdesk/superdesk-core/pull/2388
> [SDESK-6609] Support updating Events & Planning on ingest

- server/planning/feed_parsers/events_ml.py
- server/planning/feed_parsers/events_ml_test.py
- server/planning/feed_parsers/fixtures/events_ml_259270.xml
- server/planning/feed_parsers/utils.py
- server/planning/feed_parsers/utils_test.py
> handle missing time and duration field in eventsml parser

- server/planning/feed_parsers/superdesk_planning_xml.py
- setup.cfg
This allows inherited classes to overwrite it, and optionally skip certain coverages from the ingest
> [STTNHUB-188] ingest(planning_xml): Generate coverage details in separate function

- server/planning/events/events_post.py
- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_sample.json
- server/planning/feed_parsers/onclusive_tests.py
- server/planning/output_formatters/utils.py
- server/planning/utils.py
> parse contacts info from onclusive api

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_sample.json
- server/planning/feed_parsers/onclusive_tests.py
> parse language from onclusive

- server/planning/output_formatters/json_event.py
- server/planning/output_formatters/json_planning.py
- server/planning/output_formatters/json_utils.py
- server/planning/tests/output_formatters/json_event_test.py
> translate all CV names in the json output

- server/planning/common.py
- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
also change the api error handling and retry on 400 which happens sometimes
CPNHUB-198
> add buffer to onclusive api call when fetching updates

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
> ignore embargoed events from onclusive

- server/planning/autosave.py
- server/planning/item_lock.py
Depends on https://github.com/superdesk/superdesk-core/pull/2435
> [SDCP-667] Unlock items by user on users last session end

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
> use timezone info when checking embargoed time from onclusive

- server/planning/feed_parsers/onclusive.py
> check all timezones when parsing onclusive

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
- server/planning/feeding_services/onclusive_api_service.py
when the event started during the hour when there was daylight savings switch for a timezone, so rather work with utc date.
SDCP-688
> there was an error in timezone detection

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
> set language for onclusive events based on product

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
those are currently using London timezone, not utc.
SDCP-697
> fix timestamps from onclusive

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_sample.json
- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
use `/date` api instead of `/between`
and log imported events into a text file so we can check that if needed.
SDCP-699
> use /date api for initial import from onclusive

- server/planning/io/ingest_rule_handler.py
Multiple posts will still occur if a Calendar or Agenda is to be added in the ingest rule (due to the separation of ingest, and executing routing rules)
> [SDESK-6829] fix(ingest_rule): Skip autopost action if item is already posted

- client/components/Events/ManageEventTemplatesModal.tsx
> Fix event template

- client/utils/ui.tsx
> Fix show modal

- client/actions/agenda.ts
- client/actions/events/ui.ts
- client/api/editor/item_events.ts
> copy language and translation when creating a planning from event and vice versa

- client/components/fields/editor/base/dynamicTextTypeField.tsx
- client/components/fields/editor/base/multilingualText.tsx
- client/components/fields/editor/base/text.tsx
> implement slugline autocomplete

- server/features/search_multilingual.feature
- server/planning/events/events.py
- server/planning/planning/planning.py
- server/planning/search/queries/common.py
Also fixed a bug where the main `language` field would be set to system default instead of first value in `languages` field
> [SDBELGA-742] improve(api): Support searching languages field

- client/actions/agenda.ts
- client/actions/events/ui.ts
- client/actions/tests/agenda_test.ts
- client/api/editor/item_events.ts
- client/globals.d.ts
- client/utils/strings.tsx
- package-lock.json
- package.json
SDESK-7001
* refactored code to only have one function for creating planning item from event
* changed how fields are copied so when there are mapped fields, translations are mapped too
> Planning copying translations v2

- client/components/fields/editor/EventRelatedPlannings/AddNewCoverages.tsx
- client/components/fields/editor/EventRelatedPlannings/CoverageRowForm.tsx
- client/components/fields/editor/EventRelatedPlannings/EmbeddedCoverageForm.tsx
- client/components/fields/editor/EventRelatedPlannings/EventRelatedPlannings.tsx
- client/components/fields/editor/EventRelatedPlannings/RelatedPlanningItem.tsx
> add language field inside of coverage

- client/components/Assignments/AssignmentItem/AssignmentItem_test.tsx
- client/components/Assignments/AssignmentItem/index.tsx
- client/components/Assignments/AssignmentPreviewContainer/AssignmentPreviewHeader.tsx
- client/components/Coverages/CoverageEditor/CoverageFormHeader.tsx
- client/components/Coverages/CoverageIcons.tsx
- client/components/Coverages/CoverageItem.tsx
- client/components/LockContainer/LockContainerPopup.tsx
- client/components/LockContainer/index.tsx
- client/components/UI/Form/SelectUserInput/SelectUserPopup.tsx
- client/components/UI/Form/SelectUserInput/index.tsx
- client/components/UserAvatar/index.tsx
- client/components/index.ts
- package-lock.json
- package.json
SDBELGA-739
REQUIRES https://github.com/superdesk/superdesk-ui-framework/pull/800
Avatars are replaced with ones from ui-framework. On ui-framework side they're modified to accept custom body while maintaining ui-framework features like online and admin indicators.
> Use custom avatars

- client/apps/Planning/PlanningListSubNav.tsx
- package-lock.json
- package.json
> Show sign off and allow to search by it when selecting assigned user filter

- server/planning/planning/planning.py
https://github.com/superdesk/superdesk-stt/pull/40
> update coverage flags fields schema as support unknown fields [STTNHUB-198]

- client/selectors/tests/events_test.ts
- client/utils/events.ts
it wouldn't show events on days where
there would be no other event starting.
SDCP-711
> fix events not visible on end date

- .fireq.json
- server/features/search_autocomplete.feature
- server/planning/__init__.py
- server/planning/events/events_schema.py
- server/planning/planning/planning.py
- server/planning/search/planning_autocomplete.py
Depends on https://github.com/superdesk/superdesk-core/pull/2478
> [SDESK-7062] Add Event, Planning & Coverages to autocomplete suggestions

- .dockerignore
- e2e/docker-compose.yml
- e2e/server/Dockerfile
- e2e/server/core-requirements.txt
- e2e/server/docker/start.sh
- e2e/server/requirements.txt
- e2e/server/settings.py
to run use:
```bash
$ cd e2e
$ docker-compose build
$ docker-compose up
```
> add setup for e2e server docker

- client/components/fields/editor/base/numberSelect.tsx
> Manage Events & Planning Filters priority drop down list loads behind its window

- client/actions/main.ts
> When navigating away from planning the selected drop down filter is not retained

- server/planning/planning/planning.py
> fix creation of planning items via ingest

- client/api/ui/list.ts
> Selection of Planning filter is lost on scrolling down and up

- server/planning/events/events_schema.py
> add related_items to events schema

- client/components/PlanningTemplatesModal/PlanningTemplatesModal.tsx
- client/components/PlanningTemplatesModal/TemplatesListView.tsx
> Sort calendar items alphabetically, add a no-calendar group to handle templates without calendars field data

- client/components/PlanningTemplatesModal/TemplatesListView.tsx
> Make template search case insensitive

- client/components/ItemActionConfirmation/forms/updateRecurringEventsForm.tsx
PR based on latest comment :- https://sofab.atlassian.net/browse/SDBELGA-769?focusedCommentId=127916
> Fix: Empty modal showing up when we add a coverage to an event [SDBELGA-769]

- server/planning/content_profiles/utils.py
- server/planning/events/events_post.py
- server/planning/events/events_tests.py
- server/planning/planning/planning.py
- server/planning/types/content_profiles.py
If the config is enabled in the EventProfile
> [SDESK-7191] fix: Autopost Planning linked to posted Event when created from list view

- server/planning/assignments/assignments.py
- server/planning/tests/utils_tests.py
- server/planning/utils.py
https://github.com/superdesk/superdesk-belga/pull/444
> Update notifications data for belga specfic templates [SDBELGA-781]

- client/api/planning.ts
- client/components/MultiSelectActions.tsx
- client/components/UI/SubNav/SlidingToolBar.tsx
- client/interfaces.ts
> Implement Bulk add to workflow, improve SlidingToolbar types

- server/planning/events/events.py
- server/planning/planning/planning.py
[https://github.com/superdesk/superdesk-core/pull/2558](https://github.com/superdesk/superdesk-core/pull/2558)
> add new should_udpate func [SDCP-742]

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
https://github.com/superdesk/superdesk-cp/pull/233
> Onclusive parse new key for event status mapping [SDCP-749]

- server/planning/events/events.py
- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
- server/planning/tests/events_service_test.py
> update events during ingest if name/subject changes

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
> allow removing contact email/phone via update

- server/planning/commands/export_scheduled_filters.py
PR based on:- [comment](https://sofab.atlassian.net/browse/SDESK-7264?focusedCommentId=129744)
> add start_of_week config in scheduled planning export [SDESK-7264]

- server/planning/assignments/assignments.py
- server/planning/planning/planning.py
- server/planning/planning_notifications.py
- server/planning/templates/assignment_mail_subject.txt
https://github.com/superdesk/superdesk-belga/pull/476
> use name instead of slugline for templates data based on new config [SDBELGA-804]

- package-lock.json
- package.json
> update ui framework version
