superdesk/superdesk-planning

- .travis.yml
- Makefile
- server/behave.ini
- server/features/coverage.feature
- server/features/events.feature
- server/features/locations.feature
- server/features/planning.feature
- server/planning/__init__.py
- server/planning/coverage.py
- server/planning/events.py
- server/planning/locations.py
- server/planning/planning.py
- server/requirements.txt
Implementing schema only based on:
IPTC-G2-Implementation_Guide version 2.21
(https://www.iptc.org/std/NewsML-G2/latest/IPTC-G2-Implementation_Guide)
Section 15 (EventsML-G2) - 16 (Editorial Planning)
What is included in this update, and please review for:
- All necessary fields are represented, and using appropriate field types for Planning Items,  which subsequently include coverage sets and coverage items (Locations and Events were added in previous PRs).  
- Any additional internal fields (like guid, unique_name, etc) are present.
- Behave test for basic GETs and POSTs
What is NOT included in this update:
- GUID generate functions (this will come in a separate PR later)
- Detailed behave testing for GETs, POSTs, PUTs, UPDATEs
- Predefined lookup values
- Additional validators for …
> feature(server): events, locations, and planning models

- package.json
latest version react-geosuggest fixes issue with parent form submission on search button click.
> chore(nominatim): use latest version for thnkloud9 fork

- client/actions/planning.js
- client/components/EventsList/_test.jsx
- client/components/PlanningItem.jsx
- client/containers/EditPlanningPanelContainer/index.jsx
- client/containers/PlanningPanelContainer/index.jsx
- client/containers/tests/SelectAgenda_test.jsx
- client/selectors/index.js
- client/selectors/tests/index_test.js
and use another selector to retrieve events when needed without
modifying the planning object structure.
> Keep events in only one place in store.events

- client/actions/planning.js
- client/containers/ConfirmationModalContainer/_test.jsx
- client/containers/ConfirmationModalContainer/index.jsx
- client/containers/PlanningApp.jsx
- client/containers/PlanningPanelContainer/_test.jsx
- client/containers/PlanningPanelContainer/index.jsx
- client/containers/index.js
- client/controllers/PlanningController.js
- client/utils/index.js
This adds a new ConfirmationModalContainer, which can be used like that:
```
dispatch(actions.showModal({
modalType: 'CONFIRMATION',
modalProps: {
body: `Are you sure you want to delete this planning?`,
action: () => dispatch(actions.deletePlanning(planning)),
},
}))
```
SDESK-985
> Ask a confirmation for planning deletion

- package.json
- server/requirements.txt
pydocstyle 2.0.0 is not compatible with flake8-docstrings.
> Don't use pydocstyle 2.0.0

- server/planning/events.py
- server/planning/feed_parsers/ics_2_0.py
- server/planning/planning.py
Set to event ending date, and remove it when the event is linked to a planning
> Overwrite event expiry date SDESK-1167

- client/actions/agenda.js
- client/actions/planning/api.js
- client/actions/planning/tests/api_test.js
- client/components/PlanningList/index.jsx
- client/components/PlanningPanelContainer/_test.jsx
This fix a bug that was preventing to refresh the planning list when the selected agenda was empty.
SDESK-1616
> Open an Empty Agenda

- client/actions/planning/api.js
- client/actions/planning/tests/api_test.js
- `exists` query is not available in elasticsearch 1.7
> (fix) Fixing elasticsearch query for filtering planning items with no agenda.

- client/actions/agenda.js
- client/actions/planning/api.js
- client/actions/planning/notifications.js
- client/actions/planning/tests/api_test.js
- client/actions/planning/tests/notifications_test.js
- client/actions/planning/tests/ui_test.js
- client/actions/planning/ui.js
- client/actions/tests/agenda_test.js
- client/components/PlanningItem/index.jsx
- client/components/PlanningItem/style.scss
- client/components/PlanningPanelContainer/_test.jsx
- client/components/PlanningPanelContainer/index.jsx
- client/components/SearchBar/index.jsx
- client/constants/planning.js
- client/reducers/planning.js
- client/reducers/tests/planning_test.js
- client/selectors/index.js
- client/selectors/tests/index_test.js
- client/utils/index.js
- client/utils/planning.js
- client/utils/testUtils.js
- server/features/coverage.feature
- server/features/planning.feature
- server/features/planning_spike.feature
- server/planning/coverage.py
- server/planning/planning.py
- server/requirements.txt
- Includes no default coverage when Planning Item is created
- Schedule date of coverage is not compulsory.
- If coverage date is not available on any of the coverages then `planning item date`  is used for sorting and filtering.
- `planning item date` is `event start date` for planning items created from associated event and for ad-hoc planning item the `planning item date` is current date time.
> [SDESK-1563] Use scheduled date(s) of Coverage(s) for time filtering planning views

- package.json
Following https://github.com/superdesk/superdesk-client-core/pull/1847
But there are still some outdated packages
```
(env) root@sd:/opt/superdesk/planning# npm outdated
Package                          Current      Wanted       Latest  Location
istanbul-instrumenter-loader       0.2.0       0.2.0        3.0.0  superdesk-planning
react-addons-shallow-compare      15.5.2      15.5.2       15.6.0  superdesk-planning
react-bootstrap                  0.30.10     0.30.10       0.31.3  superdesk-planning
react-datepicker                  0.41.1      0.41.1       0.55.0  superdesk-planning
react-debounce-input               2.4.2       2.4.2        3.0.1  superdesk-planning
react-select                  1.0.0-rc.5  1.0.0-rc.5  1.0.0-rc.10  superdesk-planning
redux-form …
```
> Update packages following "superdesk-client-core" updates

- client/actions/events/api.js
- client/actions/events/notifications.js
- client/actions/events/tests/notifications_test.js
- client/actions/events/tests/ui_test.js
- client/actions/events/ui.js
- client/components/ItemActionConfirmation/forms/updateTimeForm.jsx
- client/constants/events.js
- server/features/events_recurring.feature
- server/features/events_reschedule.feature
- server/features/events_update_time.feature
- server/planning/events/__init__.py
- server/planning/events/events.py
- server/planning/events/events_base_service.py
- server/planning/events/events_reschedule.py
- server/planning/events/events_schema.py
- server/planning/events/events_update_time.py
* Moved 'update_time' action to a dedicated endpoint
* Created a base class for all Event action endpoints to use
* Removed code for the deprecated action of removing recurring rules from an Event
> [SDESK-2181] (fix) Ensure all affected event times are updated in the recurring series

- client/actions/agenda.js
- client/actions/tests/agenda_test.js
- client/components/AssignmentPreviewContainer/EventPreview.jsx
- client/components/Events/EventEditor/index.jsx
- client/components/Events/EventPreviewContent.jsx
- client/reducers/events.js
- client/utils/testData.js
- client/validators/index.js
- server/features/events_cancel.feature
- server/features/events_postpone.feature
- server/features/events_reschedule.feature
- server/planning/events/events_cancel.py
- server/planning/events/events_postpone.py
- server/planning/events/events_reschedule.py
- server/planning/events/events_schema.py
- server/planning/planning/planning_types.py
* Use 'ednote' instead of 'description_long' for action reasons (i.e. from Postpone/Reschedule/Cancel actions)
* Planning item also inherits ednote from the Event
> [SDESK-2569] Add Editorial Note to the Event schema

- client/controllers/PlanningController.js
* Also restore flags.authoring to it's previous value when navigating away from Planning
Requires superdesk/superdesk-client-core/pull/2178 to hide the authoring-container
> [SDESK-2536] Hide the authoring container when navigating to Planning.

- client/services/PlanningStoreService.js
ntb is using custom cvs for certain metadata in superdesk,
this will let them use same cvs in planning. this is a temporary
solution until we introduce some kind of content profiles in planning.
SDNTB-483
> allow using custom cvs for subject/genre/categories

- client/actions/autosave.js
- client/actions/locks.js
- client/actions/tests/autosave_test.js
- client/components/Autosave/index.jsx
* Removed error when creating an Event (failed to save autosave item because '_planning_item' cannot be null)
> [SDESK-2795] (fix) Don't attempt delete autosave on unlock if autosave doesn't exist

- client/utils/index.js
Hi @MarkLark86 ,
I've added [redux dev tools](https://github.com/zalmoxisus/redux-devtools-extension) (will be activated if it's installed in the browser) for non production instances. 
I think it also makes sense to apply redux logger only for non prod instances. 
Let me know if it works for you.
> [REDUX] Activate redux dev tools and redux logger for non production instances

- server/planning/output_formatters/ntb_event.py
- server/planning/tests/output_formatters/ntb_test.py
- only use definition_short for content field in output
SDNTB-500
> fix(ntb): fix ntb event xml content

- client/services/PlanningStoreService.js
@petrjasek If a vocab entry didn't have a schema field it would get into the CustomVocabularies and our subject would disappear.
> [SDESK-3179] Exclude CustomVocabularies that don't have a schema_field

- server/planning/events/events_schema.py
when there are not enough values in cv it's set to null,
but then it can't be saved.
SDESK-3759
> fix(events): make occur status nullable

- client/selectors/tests/events_test.js
- client/utils/events.js
`moment.diff` truncates the result to zero decimal places and an integer. Hence the last day of the multi-day event is not visible.
> (fix) Last day of the multi-day event was not visible in the events list.

- client/services/PlanningStoreService.js
ingest providers were fetched using a limit of 200 items. As a result,
instances where number of providers was bigger were not displaying all of
them.
This commit fixes it by using `getAll` instead of `query`
fix SDNTB-572
> [client]Fix gathering of ingest providers

- client/services/AssignmentsService.js
- client/services/tests/AssignmentsService_test.js
- client/utils/testData.js
- server/planning/assignments/__init__.py
* Add a system setting to control which desks to display the fulfil modal
> (fix) Limit assignments in fulfil modal to the content type

- client/services/AssignmentsService.js
- client/services/tests/AssignmentsService_test.js
- server/planning/assignments/__init__.py
* Fix bug with 'PLANNING_FULFIL_ON_PUBLISH_FOR_DESKS' config if the config is an empty string
> [SDESK-4273] Use exact slugline match in Fulfil Assignment on Publish

- package.json
This fixes the issues with unit tests failing after upgrading to React v16.8.x
> (fix): Update enzyme-adapter-react-16

- client/actions/assignments/api.js
- client/actions/assignments/notifications.js
- client/actions/assignments/tests/api_test.js
- client/actions/assignments/tests/notification_test.js
- client/actions/assignments/tests/ui_test.js
- client/actions/assignments/ui.js
- client/apps/Assignments/AssignmentList.jsx
- client/apps/Assignments/AssignmentsSubNav.jsx
- client/apps/Assignments/FulfilAssignmentUi.jsx
- client/components/Assignments/AssignmentGroupList.jsx
- client/components/Assignments/AssignmentItem/index.jsx
- client/components/Assignments/SubNavBar.jsx
- client/constants/assignments.js
- client/controllers/AssignmentController.js
- client/controllers/FulfilAssignmentController.js
- client/reducers/assignment.js
- client/reducers/tests/assignment_test.js
- client/selectors/assignments.js
- client/selectors/tests/assignments_test.js
- client/services/AssignmentsService.js
- client/services/tests/AssignmentsService_test.js
- client/styles/index.scss
- client/utils/assignments.js
- client/utils/testData.js
- client/utils/tests/assignments_test.js
- package.json
* (fix): Use items desk not the selected desk when determining if to fulfill assignment on publish
> [SDESK-4529][SDESK-4534] Show current and future only assignments in the Fulfill modal

- client/actions/tests/autosave_test.js
- client/constants/autosave.js
- client/utils/testData.js
When you duplicate an event, autosave does not send `duplicate_from` which brakes a relation between events.
SDNTB-599
> Fix event duplicate.

- server/features/planning_export.feature
- server/planning/planning_article_export.py
user can add `{{content}}` placeholder to fields in content template
and it will be replaced by generated content.
SDBELGA-186
> control via article template where generated content is inserted

- client/components/UI/Form/SelectMetaTermsInput/index.jsx
- client/components/UI/TermsList.jsx
SDNTB-613
Values from the same array are used both for subject and category fields thus removing items by index can't be used.
> Fix buggy behaviour when trying to remove subjects from event and planning item

- client/components/Assignments/AssignmentEditor.jsx
- client/components/Assignments/AssignmentPreviewContainer/AssignmentPreview.jsx
- client/components/Contacts/ContactLabel.jsx
- client/components/Contacts/SelectSearchContactsField/SelectListPopup.jsx
- client/components/Contacts/SelectSearchContactsField/index.jsx
- client/components/Coverages/CoverageEditor/CoverageForm.jsx
- client/components/Coverages/CoveragePreview/index.jsx
- client/components/Coverages/ScheduledUpdate/ScheduledUpdateForm.jsx
- client/components/Coverages/ScheduledUpdate/index.jsx
- client/components/Events/tests/EventPreviewContent_test.jsx
- client/components/UI/SearchField/index.jsx
- client/utils/assignments.js
* External Contact on the Coverage Assignment Details modal should be a prepopulated drop list search as for Desk and User
* Change the label from 'External Contact' to 'Assigned Provider'
* Change the hint text to 'Search provider contacts'
* The Coverage Provider Contact tile persists (as read only) if the assignee type is reverted from Coverage Provider to user
> [SDESK-4766] UX improvements for coverage provider contact

- server/features/publish.feature
- server/planning/events/events_files.py
In mongo:
Production API response:
> SDBELGA-262 [EVENT FILES] Save additional file information.

- server/planning/planning_notifications.py
- server/planning/planning_notifications_test.py
See [details here](https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api?utm_medium=email&utm_source=newsletter&utm_campaign=fy21-Q205-changelog)
> fix(slack) change deprecated slack API call

- client/components/PlanningDetailsWidget.tsx
- client/components/UI/Preview/ExpandableText.jsx
PlanningDetails widget threw the React error code https://reactjs.org/docs/error-decoder.html/?invariant=321
This may be happening because Superdesk has React 16.9 while UI-Framework has 16.8
as the UI-Framework is bundling React inside its dist/superdesk-ui.bundle.js
Also added padding for this widget (SDESK-4327)
> [SDESK-5223] Replace React hooks with Class for ExpandableText component

- e2e/package-lock.json
- e2e/package.json
- server/data/vocabularies.json
Using a higher init_version than superdesk-core, and copied all entries from superdesk-core as well (from data_init/vocabularies.json)
> [SDESK-5345] Force update subscriber_types in initialize_data command

- client/apps/Assignments/AssignmentList.jsx
- client/constants/assignments.js
- client/constants/index.js
SDCP-291
`gettext` doesn't work on top level code so strings like `"There are no
assignments in progress"` where not being translated in the UI.
> Use a function to get assignments when translations are needed

- server/planning/common.py
- server/planning/output_formatters/json_event.py
- server/planning/output_formatters/json_planning.py
there was `_current_version` sent in ninjs
which is huge number and can't fit into elastic integer.
SDAN-680
> [SDAN-680] fix updating of events in newshub

- client/components/fields/editor/base/select.tsx
Replaces usage of `getDerivedStateFromProps` with `lodash.memoize` in the newer Select component
> [SDCP-528] fix: Select dropdowns failed to re-render on language change

- client/components/fields/editor/CoverageSchedule.tsx
- client/components/fields/editor/EndDateTime.tsx
- client/components/fields/editor/EventSchedule.tsx
- client/components/fields/editor/StartDateTime.tsx
SDCP-526
It was noticed by QA when testing translations, that "to be confirmed" button was missing in events and coverages even though it was present before.
> [SDCP-526] Enable date field option showToBeConfirmed in events and coverages

- client/utils/assignments.ts
- client/utils/tests/assignments_test.ts
This reverts the enforcement added in SDESK-5010 (https://github.com/superdesk/superdesk-planning/commit/0275d6ff2c577e8b12fe5b0a16cb9b4d8ab2cb83)
We should allow these actions on a Picture Assignment, even if the state is controlled externally (i.e. via AAP DC).
@marwoodandrew: do you see any issue here?
> [SDESK-6183] Allow `Reassign` or `Edit Priority` of Picture Assignments

- client/components/Coverages/CoverageEditor/CoverageForm.tsx
- client/components/Coverages/CoverageEditor/CoverageFormHeader.tsx
- client/components/Coverages/ScheduledUpdate/index.tsx
- client/components/Planning/PlanningEditor/index.tsx
- client/components/fields/editor/ScheduledUpdates.tsx
- client/utils/planning.ts
- e2e/cypress/integration/events/event_action_create_planning.spec.ts
- e2e/server/settings.py
**<cherry picked from hotfix/2.3.2 branch>**
* fix: Update coverage profile with scheduled_updates field
* fix: Pass required params to scheduled_update field
* fix: Modify scheduled_update genre regardless of scheduled date/time
> [SDESK-6174] fix(ui): Planning goes blank after adding scheduled update (#1660)

- client/utils/index.ts
The experience described in SDESK-6305 is not actually a bug but desired behaviour. The bug is actually to do with not letting the user know why they could not complete the 'Mark as Completed' action
> [SDESK-6305] fix: Extent getErrorMessage to include errors in _issues

- client/actions/events/notifications.ts
- client/actions/events/tests/notifications_test.ts
- client/actions/planning/notifications.ts
- client/actions/planning/tests/notifications_test.ts
- client/api/events.ts
- client/api/planning.ts
- client/interfaces.ts
- client/utils/events.ts
- client/utils/locks.ts
- client/utils/planning.ts
- client/utils/testApi.ts
- client/utils/tests/events_test.ts
- client/utils/tests/planning_test.ts
- client/utils/time.ts
This was causing the Editor to act as if the Event/Planning item was not locked for editing
> [SDESK-6504] fix: Ignore unlock ws notification if already unlocked

- server/planning/feeding_services/onclusive_api_service.py
- it wasn't really used because of missing `=` in the url
- it started with 100 so missed first 100 events always
> fix onclusive api offset param handling

- server/planning/events/events.py
Duplicating recuring events updates the original events with the "duplicate_to" field, the event update called _enhance_event_item on each event without passing an _id in the update. A query on the planning collection with event_item : null was made.
> [SDAAP-52] Speed up the response of the Events Post endpoint

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
it fails validation when editing those events, so rather store original id as uri and stick to objectids
uses https://github.com/superdesk/superdesk-core/pull/2417
SDCP-661
> avoid using non objectid _id for contacts from onclusive

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
we were using created time as part of id which produced duplicates like:
`urn:onclusive:2022-12-30T08:52:14.3070000:4757907`
`urn:onclusive:2022-12-30T08:52:14.5230000:4757907`
in general we don't need the date to be there so removing it to avoid any issues with those dates.
CPNHUB-184
> avoid duplicates of onclusive events

- .github/workflows/lint-server.yml
- server/planning/output_formatters/json_event.py
- server/planning/output_formatters/json_planning.py
- server/planning/output_formatters/json_utils.py
- server/planning/tests/output_formatters/json_event_test.py
- server/planning/tests/output_formatters/json_planning_test.py
> export subject name in item language

- client/actions/main.ts
- client/components/Main/CreateNewSubnavDropdown.tsx
- e2e/cypress/e2e/events/event_template.cy.ts
Also remove `dates` when creating from a Template, as these aren't desired
> fix(e2e): EventTemplates fail due to search changes in GenericHttpEntityListPageComponent

- e2e/server/requirements.txt
- server/features/autosave.feature
- server/features/events_spike.feature
- server/planning/common.py
- server/requirements.txt
We need to place a maximum default value, as event duration can cause performance issues if the duration is too long
> [NHUB-269] fix: Default MAX_MULTI_DAY_EVENT_DURATION to 1 year

- client/utils/events.ts
or any other place with negative timezone offset, that makes the events which are stored with time 00:00:00 be presented on a previous day.
SDESK-6857
> fix date in preview for all day events when in toronto

- client/components/ContentProfiles/GroupTab/GroupEditor.tsx
- client/components/fields/editor/EventSchedule.tsx
- client/components/fields/editor/Language.tsx
- client/components/fields/editor/base/selectWithFreeText.tsx
- client/components/fields/editor/base/toggle.tsx
- client/planning-extension/src/ingest_rule_autopost/AutopostIngestRuleEditor.tsx
- package-lock.json
- package.json
> Update superdesk UI framework to 3.0.14

- client/api/contentProfiles.ts
Mapping by `_id` doesn't always work. In ntb-develop test instance the Event profile is created with an ObjectID: https://github.com/superdesk/superdesk-ntb/blob/master/server/data/planning_types.json#L3.
We're already using `name` attribute when storing in Redux: https://github.com/superdesk/superdesk-planning/blob/develop/client/services/PlanningStoreService.ts#L252
> [SDNTB-804] fix(ui): Load ContentProfiles using its name not _id

- server/planning/events/events.py
- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
- keep timestamp for next run based on current start
- look for timezone not only using name but also offset
- increase buffer when getting updates (not clear if the timestamps should be utc or local, so add some extra time
- for events with no end time set it to start time and not some fake end time which might make it go visible on a next day
SDCP-688 SDCP-690
> fix onclusive ingest

- client/utils/events.ts
- client/utils/index.ts
mostly related to events with `no_end_time` flag
which have same end timestamp as start one.
SDCP-680
> fix events not visible in the UI

- client/components/Events/EventScheduleSummary/index.tsx
- client/utils/events.ts
that was the case for events with no end time
and same timezone as local one for user.
SDCP-690
> fix event date not visible in preview

- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
so it's consistent with manually created events
SDCP-696
> use languages with -CA for onclusive events

- client/components/CustomVocabulariesFields.tsx
- client/components/UI/Form/SelectMetaTermsInput/SelectFieldPopup.tsx
- client/components/fields/editor/CustomVocabularies.tsx
> fixing language in vocabulary select (multilingual mode)

- client/components/Editor/EditorGroup.tsx
- client/components/fields/editor/EventRelatedPlannings/AddNewCoverages.tsx
- client/components/fields/editor/EventRelatedPlannings/CoverageRowForm.tsx
- client/components/fields/editor/EventRelatedPlannings/EmbeddedCoverageForm.tsx
- client/components/fields/editor/EventRelatedPlannings/EventRelatedPlannings.tsx
- client/components/fields/editor/EventRelatedPlannings/RelatedPlanningItem.tsx
- client/components/fields/index.tsx
> language field inside of coverages - update

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
so we can check logs in case some event is missing
CPCN-380
> log each event id we process from onclusive

- client/components/fields/editor/base/multilingualText.tsx
Here we resolved an issue where typing in one multilingual text field unintentionally caused the first letter of the word to appear in the default language field.
issue snap-video : https://ctrlv.tv/EJHV
> fix: Prevent unintended synchronization of multilingual text fields[SDESK-7061]

- client/components/fields/style.scss
The z-index for tooltips defined in planning is at the wrong place and causes issues in Superdesk core. Removed code: 
`[data-sd-tooltip] {
z-index: 1000 !important;
opacity: 1 !important;
}`
> [SDESK-7117]

- README.md
- server/planning/output_formatters/json_planning.py
- server/planning/tests/output_formatters/json_planning_test.py
CPCN-502
uses https://github.com/superdesk/superdesk-core/pull/2502
> add assigned user/desk info to planning json

- client/components/RelatedPlannings/PlanningMetaData/RelatedPlanningListItem.tsx
- client/components/fields/editor/EventRelatedPlannings/EventRelatedPlannings.tsx
- client/components/fields/editor/EventRelatedPlannings/RelatedPlanningItem.tsx
PR based on latest comment :- https://sofab.atlassian.net/browse/SDESK-7136?focusedCommentId=126957
> Hide the text 'Agenda:No Agenda Assigned.' in the related planning section [SDESK-7136]

- client/api/ui/list.ts
- client/components/Main/FiltersBox.tsx
> Selection of Planning filter is lost on scrolling down and up - update

- client/components/ItemActionConfirmation/forms/updateRecurringEventsForm.tsx
Reverts superdesk/superdesk-planning#1921
> Revert "Fix: Empty modal showing up when we add a coverage to an event [SDBELGA-769]"

- server/planning/assignments/assignments.py
Due to incomplete `system_update` signature in Assignments service (missing `kwargs`)
> [SDESK-7163] fix: Purge assignment lock fails

- server/planning/assignments/assignments.py
- server/planning/commands/purge_expired_locks.py
- server/planning/commands/purge_expired_locks_test.py
- server/planning/utils.py
For some reason checking auth DB didn't work entirely. So going for a brute force approach, using lock datetime instead
> [SDESK-7163] improve: Use expiry datetime for purge_expired_locks command

- .fireq.json
- client/actions/events/api.ts
- client/actions/events/ui.ts
- client/actions/main.ts
- client/components/ConfirmationModal.tsx
- client/components/Events/EventScheduleSummary/index.tsx
- client/components/IgnoreCancelSaveModal.tsx
- client/components/ItemActionConfirmation/forms/updateRecurringEventsForm.tsx
- client/components/Main/ItemEditor/Editor.tsx
- client/components/Main/ItemEditor/ItemManager.ts
- client/components/Main/ItemEditor/tests/ItemManager_test.ts
- client/components/RelatedPlannings/PlanningMetaData/RelatedPlanningListItem.tsx
- client/components/fields/index.tsx
- client/components/fields/preview/EventSchedule.tsx
- client/components/fields/preview/base/PreviewSimpleListItem.tsx
- client/components/fields/preview/index.ts
- client/components/tests/IgnoreCancelSaveModal_test.tsx
- client/selectors/general.ts
- client/utils/events.ts
Also improve look and feel when rendering Event & Planning metadata in the modal
> [SDBELGA-778] fix: Show recurring Planning update method on Ignore|Cancel|Save modal

- e2e/package.json
- package-lock.json
- package.json
- server/features/events_recurring.feature
- server/planning/events/events.py
so we can later check which event is the initial one
CPCN-695
> set recurrence_id based on event _id

- README.md
- client/components/Assignments/AssignmentPreviewContainer/AssignmentPreviewContainer_test.tsx
- client/components/Assignments/AssignmentPreviewContainer/index.tsx
- client/components/fields/index.tsx
- client/components/fields/preview/RelatedArticles.tsx
- client/components/fields/preview/index.ts
- client/interfaces.ts
- server/planning/assignments/assignments_content.py
- server/planning/common.py
- server/planning/content_profiles/__init__.py
- server/planning/content_profiles/service.py
- server/planning/signals.py
- server/planning/types/__init__.py
Also:
* send a signal when starting work on an Assignment
* Make `related_items` field depend on the presence of the `EVENT_RELATED_ITEM_SEARCH_PROVIDER_NAME` config
> [SDBELGA-780] RelatedItems: Add related items to preview panels

- server/planning/events/events_tests.py
- server/planning/feeding_services/onclusive_api_service.py
- server/planning/feeding_services/onclusive_api_service_tests.py
> implement onclusive reingesting

- client/actions/events/api.ts
- client/actions/events/tests/api_test.ts
- client/actions/main.ts
- client/interfaces.ts
- client/utils/index.ts
- server/features/events_post.feature
- server/planning/events/events_post.py
- server/planning/events/events_schema.py
- server/planning/events/events_tests.py
PR based on [Comment](https://sofab.atlassian.net/browse/SDESK-7202?focusedCommentId=129158)
Previously, when related planning item validation failed, the API returned an error, which prevented the Redux state from updating and consequently not reflect the event status in the UI
so I've implemented a workaround here, as when posting an Event, if validation of Event passes and the Event is posted, we respond back to the client with a success. If associated Planning items fail validation, we catch all planning posting errors, and return those to the user along with the response
> optimize validation of related planning items when posted alongside events [SDESK-7202]

- server/planning/common.py
- server/planning/search/queries/combined.py
- server/planning/search/queries/elastic.py
- server/planning/tests/utils_tests.py
Fix items from previous week along with items from this week are also displayed
> Fix this_week filter [SDESK-7264]

- client/api/ui/list.ts
- client/components/Main/FilterSubnavDropdown.tsx
When using the next_filter from the sidenav bar (Advanced Search), the list is filtered and displays the accurate items. However, when applying filters manually, the data is not filtered correctly. The root cause was identified as the absence of the `advancedSearch.dates.range` parameter in the manual filter process. so when this param is missing, the datetime is not updated from here : https://github.com/superdesk/superdesk-planning/blob/develop/client/utils/index.ts#L690-L728
> Fix: display of accurate Items using manual filters search [SDESK-7264]

- server/planning/feed_parsers/onclusive.py
- server/planning/feed_parsers/onclusive_tests.py
CPCN-825
uses https://github.com/superdesk/superdesk-core/pull/2595
> set expiry when parsing onclusive events
